# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitopsVault < Formula
  desc "GitOps secret desensitization tool"
  homepage "https://github.com/zgfh/gitops-vault"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zgfh/gitops-vault/releases/download/v0.1.6/gitops-vault_0.1.6_darwin_amd64.tar.gz"
      sha256 "210b6d376ea64659b96f8a78e40d08a2624b98fdab17a3f616c71420bb85fc84"

      define_method(:install) do
        bin.install "gitops-vault"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zgfh/gitops-vault/releases/download/v0.1.6/gitops-vault_0.1.6_darwin_arm64.tar.gz"
      sha256 "9182f79855172dc04411c198d18ffb4420c5e43a6950f7006f9414a75984412a"

      define_method(:install) do
        bin.install "gitops-vault"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zgfh/gitops-vault/releases/download/v0.1.6/gitops-vault_0.1.6_linux_amd64.tar.gz"
      sha256 "9afa4ab746f3b052f15ca5230368f02313b4d50ad2f6fd0a9f28b79ff078ee29"
      define_method(:install) do
        bin.install "gitops-vault"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zgfh/gitops-vault/releases/download/v0.1.6/gitops-vault_0.1.6_linux_arm64.tar.gz"
      sha256 "acf7e93dfb2d9dfb5279204e9103a641e9c35fd58fff29d95aa238a96427f711"
      define_method(:install) do
        bin.install "gitops-vault"
      end
    end
  end

  test do
    system "#{bin}/gitops-vault", "--version"
  end
end
